Map<String, String> ar = {
  'app_title': 'تطبيق الحجوزات',
  'login': 'تسجيل الدخول',
  'register': 'تسجيل جديد',
  'logout': 'تسجيل الخروج',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'full_name': 'الاسم الكامل',
  'phone': 'رقم الهاتف',
  'country': 'الدولة',
  'search': 'بحث',
  'hotels': 'الفنادق',
  'flights': 'الرحلات',
  'packages': 'الباقات',
  'hotel': 'فندق',
  'flight': 'رحلة',
  'package': 'باقة',
  'bookings': 'حجوزاتي',
  'profile': 'الملف الشخصي',
  'home': 'الرئيسية',
  'book_now': 'احجز الآن',
  'price': 'السعر',
  'rating': 'التقييم',
  'stars': 'نجوم',
  'nights': 'ليلة',
  'check_in': 'تاريخ الدخول',
  'check_out': 'تاريخ الخروج',
  'confirm_booking': 'تأكيد الحجز',
  'booking_confirmed': 'تم تأكيد الحجز',
  'cancel_booking': 'إلغاء الحجز',
  'payment': 'الدفع',
  'payment_method': 'طريقة الدفع',
  'card': 'بطاقة',
  'cash': 'نقدي',
  'total': 'الإجمالي',
  'discount': 'خصم',
  'final_price': 'السعر النهائي',
  'no_results': 'لا توجد نتائج',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'success': 'نجح',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'edit': 'تعديل',
  'delete': 'حذف',
  'details': 'التفاصيل',
  'amenities': 'المرافق',
  'description': 'الوصف',
  'city': 'المدينة',
  'address': 'العنوان',
  'departure': 'المغادرة',
  'arrival': 'الوصول',
  'duration': 'المدة',
  'airline': 'شركة الطيران',
  'flight_class': 'درجة الرحلة',
  'economy': 'اقتصادية',
  'business': 'رجال أعمال',
  'room_type': 'نوع الغرفة',
  'max_guests': 'عدد الأشخاص',
  'available': 'متوفر',
  'not_available': 'غير متوفر',
  'create_account': 'إنشاء حساب',
  'sign_up_subtitle': 'سجل الآن للبدء',
  'enter_full_name': 'الرجاء إدخال الاسم الكامل',
  'enter_email': 'الرجاء إدخال البريد الإلكتروني',
  'invalid_email': 'بريد إلكتروني غير صالح',
  'enter_phone': 'الرجاء إدخال رقم الهاتف',
  'enter_country': 'الرجاء إدخال اسم الدولة',
  'already_have_account': 'لديك حساب بالفعل؟ ',
  'please_login_first': 'الرجاء تسجيل الدخول أولاً',
  'switch_language': 'تغيير اللغة',
  'welcome_back': 'مرحباً بعودتك!',
  'sign_in_continue': 'سجل الدخول للمتابعة',
  'dont_have_account_text': 'ليس لديك حساب؟ ',
  'find_perfect_stay': 'جد إقامتك المثالية',
  'cancel_booking_confirm': 'هل أنت متأكد من رغبتك في إلغاء هذا الحجز؟',
  'payment_failed': 'فشلت عملية الدفع. يرجى المحاولة مرة أخرى.',
  'select_check_in_out': 'يرجى اختيار تاريخ الدخول والخروج',
  'hotel_not_found': 'الفندق غير موجود',
  'select_date': 'اختر التاريخ',
  'confirmed': 'مؤكد',
  'cancelled': 'ملغي',
  'pending': 'قيد الانتظار',
  'status': 'الحالة',
  'booking_details': 'تفاصيل الحجز',
  'date': 'التاريخ',
  'type': 'النوع',
  'booking_id': 'حجز',
  'upcoming_booking': 'حجز قريب',
  'booking_reminder_text':
      'لديك حجز مؤكد اقترب موعده. لا تنسى مراجعة التفاصيل.',
  'view_details': 'عرض التفاصيل',
  'edit_profile': 'تعديل الملف الشخصي',
  'about_app': 'حول التطبيق',
  'delete_account': 'حذف الحساب',
  'account_settings': 'إعدادات الحساب',
  'general_settings': 'إعدادات عامة',
  'support': 'الدعم والمساعدة',
  'notifications': 'التنبيهات',
  'privacy_policy': 'سياسة الخصوصية',
  'terms_of_service': 'شروط الخدمة',
  'version': 'الإصدار',
  'dark_mode': 'النمط الليلي',
  'select_language': 'اختر اللغة',
  'arabic': 'العربية',
  'english': 'الإنجليزية',
  'about_app_description':
      'تطبيق حجوزات عصري يوفر أفضل الخدمات للسفر والإقامة.',
  'cancellation_reason': 'سبب الإلغاء',
  'select_reason': 'اختر سبب الإلغاء',
  'reason_changed_mind': 'غيرت رأيي',
  'reason_better_price': 'وجدت سعراً أفضل',
  'reason_travel_plans': 'تغيرت خطط السفر',
  'reason_booking_error': 'خطأ في الحجز',
  'reason_other': 'سبب آخر',
  'enter_reason': 'أدخل سبب الإلغاء هنا...',
  'active_bookings': 'الحجوزات الحالية',
  'past_bookings': 'الحجوزات السابقة',
  'selected': 'مختار',
  'open_in_maps': 'فتح الخريطة',
  'location': 'الموقع',
  'subject': 'الموضوع',
  'message_label': 'الرسالة',
  'send_request': 'إرسال الطلب',
  'support_requests': 'طلبات الدعم والمساعدة',
  'new_request': 'طلب جديد',
  'priority': 'الأولوية',
  'low': 'منخفضة',
  'medium': 'متوسطة',
  'high': 'عالية',
  'request_sent_success': 'تم إرسال طلبك بنجاح. سنرد عليك في أقرب وقت.',
  'request_sent_error': 'فشل إرسال الطلب. يرجى المحاولة مرة أخرى.',
  'no_support_requests': 'ليس لديك طلبات دعم سابقة.',
  'enter_subject': 'يرجى إدخال موضوع الطلب',
  'enter_message': 'يرجى إدخال نص الرسالة',
  'attachments': 'المرفقات',
  'attachments_desc': 'عرض الوثائق والمرفقات المرتبطة',
  'favorites': 'المفضلة',
  'most_liked': 'الأكثر إعجاباً',
  'all_hotels': 'جميع الفنادق',
  'sort_by': 'ترتيب',
  'add_to_favorites': 'أضف إلى المفضلة',
  'remove_from_favorites': 'إزالة من المفضلة',
  'favorites_stats': 'إحصائيات المفضلة',
  'total_favorites': 'إجمالي المفضلة',
  'top_hotel': 'أكثر فندق إعجاباً',
  'no_favorites': 'لا توجد فنادق مفضلة حتى الآن',
  'no_favorites_desc': 'تصفح الفنادق واضغط على أيقونة القلب لإضافتها هنا',
  'likes': 'إعجاب',
  'paid': 'تم الدفع',
  'unpaid': 'لم يتم الدفع',
  'payment_status': 'حالة الدفع',
  'room_number': 'رقم الغرفة',
  'embassy': 'سفارة',
  'travel_purpose': 'الغرض من السفر',
  'embassy_appointment': 'موعد السفارة',
  'required_documents': 'المستندات المطلوبة',
  'interview': 'المقابلة (إن وجدت)',
  'visa_decision': 'القرار',
  'package_details': 'تفاصيل الباقة الشاملة',
  'flight_booking': 'حجز الطيران',
  'hotel_booking': 'حجز الفندق',
  'tours_activities': 'الأنشطة والجولات',
  'documents_received': 'الوثائق المستلمة',
};
