Map<String, String> en = {
  'app_title': 'Booking App',
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'email': 'Email',
  'password': 'Password',
  'full_name': 'Full Name',
  'phone': 'Phone',
  'country': 'Country',
  'search': 'Search',
  'hotels': 'Hotels',
  'flights': 'Flights',
  'packages': 'Packages',
  'hotel': 'Hotel',
  'flight': 'Flight',
  'package': 'Package',
  'bookings': 'My Bookings',
  'profile': 'Profile',
  'home': 'Home',
  'book_now': 'Book Now',
  'price': 'Price',
  'rating': 'Rating',
  'stars': 'Stars',
  'nights': 'Nights',
  'check_in': 'Check In',
  'check_out': 'Check Out',
  'confirm_booking': 'Confirm Booking',
  'booking_confirmed': 'Booking Confirmed',
  'cancel_booking': 'Cancel Booking',
  'payment': 'Payment',
  'payment_method': 'Payment Method',
  'card': 'Card',
  'cash': 'Cash',
  'total': 'Total',
  'discount': 'Discount',
  'final_price': 'Final Price',
  'no_results': 'No Results',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'save': 'Save',
  'cancel': 'Cancel',
  'edit': 'Edit',
  'delete': 'Delete',
  'details': 'Details',
  'amenities': 'Amenities',
  'description': 'Description',
  'city': 'City',
  'address': 'Address',
  'departure': 'Departure',
  'arrival': 'Arrival',
  'duration': 'Duration',
  'airline': 'Airline',
  'flight_class': 'Flight Class',
  'economy': 'Economy',
  'business': 'Business',
  'room_type': 'Room Type',
  'max_guests': 'Max Guests',
  'available': 'Available',
  'not_available': 'Not Available',
  'create_account': 'Create Account',
  'sign_up_subtitle': 'Sign up now to get started',
  'enter_full_name': 'Please enter full name',
  'enter_email': 'Please enter email',
  'invalid_email': 'Invalid email',
  'enter_phone': 'Please enter phone',
  'enter_country': 'Please enter country',
  'already_have_account': 'Already have an account? ',
  'please_login_first': 'Please login first',
  'switch_language': 'Switch Language',
  'welcome_back': 'Welcome back!',
  'sign_in_continue': 'Sign in to continue',
  'dont_have_account_text': 'Don\'t have an account? ',
  'find_perfect_stay': 'Find your perfect stay',
  'cancel_booking_confirm': 'Are you sure you want to cancel this booking?',
  'payment_failed': 'Payment failed. Please try again.',
  'select_check_in_out': 'Please select check-in and check-out dates',
  'hotel_not_found': 'Hotel not found',
  'select_date': 'Select date',
  'confirmed': 'Confirmed',
  'cancelled': 'Cancelled',
  'pending': 'Pending',
  'status': 'Status',
  'booking_details': 'Booking Details',
  'date': 'Date',
  'type': 'Type',
  'booking_id': 'Booking',
  'upcoming_booking': 'Upcoming Booking',
  'booking_reminder_text':
      'You have an upcoming confirmed booking. Don\'t forget to review the details.',
  'view_details': 'View Details',
  'edit_profile': 'Edit Profile',
  'about_app': 'About App',
  'delete_account': 'Delete Account',
  'account_settings': 'Account Settings',
  'general_settings': 'General Settings',
  'support': 'Support & Help',
  'notifications': 'Notifications',
  'privacy_policy': 'Privacy Policy',
  'terms_of_service': 'Terms of Service',
  'version': 'Version',
  'dark_mode': 'Dark Mode',
  'select_language': 'Select Language',
  'arabic': 'Arabic',
  'english': 'English',
  'about_app_description':
      'A modern booking application providing top-tier travel and stay services.',
  'cancellation_reason': 'Cancellation Reason',
  'select_reason': 'Select Cancellation Reason',
  'reason_changed_mind': 'Changed my mind',
  'reason_better_price': 'Found a better price',
  'reason_travel_plans': 'Travel plans changed',
  'reason_booking_error': 'Booking error',
  'reason_other': 'Other',
  'enter_reason': 'Enter your reason here...',
  'active_bookings': 'Active Bookings',
  'past_bookings': 'Past Bookings',
  'selected': 'Selected',
  'open_in_maps': 'Open in Map',
  'location': 'Location',
  'subject': 'Subject',
  'message_label': 'Message',
  'send_request': 'Send Request',
  'support_requests': 'Support & Help Requests',
  'new_request': 'New Request',
  'priority': 'Priority',
  'low': 'Low',
  'medium': 'Medium',
  'high': 'High',
  'request_sent_success': 'Request sent successfully. We will reply soon.',
  'request_sent_error': 'Failed to send request. Please try again.',
  'no_support_requests': 'No previous support requests found.',
  'enter_subject': 'Please enter subject',
  'enter_message': 'Please enter message',
  'attachments': 'Attachments',
  'attachments_desc': 'View associated documents and attachments',
  'favorites': 'Favorites',
  'most_liked': 'Most Liked',
  'all_hotels': 'All Hotels',
  'sort_by': 'Sort by',
  'add_to_favorites': 'Add to Favorites',
  'remove_from_favorites': 'Remove from Favorites',
  'favorites_stats': 'Favorites Statistics',
  'total_favorites': 'Total Favorites',
  'top_hotel': 'Most Liked Hotel',
  'no_favorites': 'No favorite hotels yet',
  'no_favorites_desc': 'Browse hotels and tap the heart icon to add them here',
  'likes': 'likes',
  'paid': 'Paid',
  'unpaid': 'Unpaid',
  'payment_status': 'Payment Status',
  'room_number': 'Room Number',
  'embassy': 'Embassy',
  'travel_purpose': 'Travel Purpose',
  'embassy_appointment': 'Embassy Appointment',
  'required_documents': 'Required Documents',
  'interview': 'Interview (if any)',
  'visa_decision': 'Decision',
  'package_details': 'Full Package Details',
  'flight_booking': 'Flight Booking',
  'hotel_booking': 'Hotel Booking',
  'tours_activities': 'Tours & Activities',
  'documents_received': 'Documents Received',
};
